---


- name: debian | Add apt key
  apt_key:
    url: "{{apt_key}}"

- name: debian | Adding PowerBroker Identity Service repo
  get_url:
    url: "{{pbis_apt_repo}}"
    dest: "/etc/apt/sources.list.d/pbiso.list"
    mode: 0744

- name: debian | update
  apt: update_cache=yes

- name: debian | Installing pbis-open from apt repo
  apt: name=pbis-open update_cache=yes state=latest

- name: debian | checking the Domain status
  shell: /opt/pbis/bin/lsa get-status |grep Netbios |awk '{print $3}'
  register: domain_status

- name: debian | Joining host to AD domain
  command: 'domainjoin-cli join --ou {{ ad_ou }} {{ ad_domain }} {{ ad_user }} {{ ad_password }}'
  when:  domain_status.stdout != "{{ ad_domain_netbios }}"

- name: debian | setting includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: debian | granting sudo rights to Domain Groups
  lineinfile:
    dest: /etc/sudoers
    line: "%{{ ad_domain_netbios }}\\\\{{ item }} ALL=(ALL:ALL) ALL"
    state: present
    validate: 'visudo -cf %s'
  with_items: domain_sudo_groups

##########################
######pbis condfig########
#sudo /opt/pbis/bin/config UserDomainPrefix $domain
#sudo /opt/pbis/bin/config AssumeDefaultDomain true
#sudo /opt/pbis/bin/config LoginShellTemplate /bin/bash
#sudo /opt/pbis/bin/config HomeDirTemplate %H/%U
#sudo /opt/pbis/bin/config RequireMembershipOf "$domain\\$securitygroup"
###########################